[registry]
default = "forge"

[registries.forge]
index = "sparse+https://urm.nvidia.com/artifactory/api/cargo/sw-ngc-forge-cargo-local/index/"

[registries.cratesio]
index = "https://github.com/rust-lang/crates.io-index"

[package]
publish = "forge"
